### ISSUE TITLE
Add get path param name helper

### ISSUE THREAD

**Issue by alexander-melentyev** [go-dummy/dummy#123]
### Example
```go
func GetPathParamName(param string) string {
    if strings.HasPrefix(param, "{") && strings.HasSuffix(param, "}") {
        return param[1:len(param)-1]
    }
    
    return ""
}
```
Don't forget test

**Comment by p12s** [comment]
Привет, твоя функция обрабатывает строку так:
"{some string}" => "some string"
а другие варианты:
"some string}" => ""
"some string" => ""
---
будет ли правильнее оставлять строку исходной, если скобок нет? 
"{some string" => "some string"
"some string}" => "some string"
"some string" => "some string"
или придерживаться строго твоего варианта?

**Comment by p12s** [comment]
и еще, реализовывать функцию в файле  
internal/server/handler.go ?
единственное подходящее по-смыслу место

**Comment by alexander-melentyev** [comment]
@p12s, привет!
Дело в том, что в OpenAPI спецификации параметры в пути описывают именно в фигурных скобках. То есть если встречается что-то по-типу "some string}" - то это явно не параметр, а скорей всего ошибка в спецификации. 
Да, здесь internal/server/handler.go

**Comment by p12s** [comment]
> Дело в том, что в OpenAPI спецификации параметры в пути описывают именно в фигурных скобках. То есть если встречается что-то по-типу "some string}" - то это явно не параметр, а скорей всего ошибка в спецификации.
Ок, тогда другие варианты не буду предусматривать

**Comment by p12s** [comment]
имею ввиду не буду обрезать, если одна скобка

**Comment by alexander-melentyev** [comment]
И не нужно. Нужно определить есть ли во входных данных вначале скобка и в конца, и взять все что в скобках, в остальных случаях - пустая строка
